name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision tqdm pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Train model
      run: |
        python train.py --epochs 1 --target-accuracy 95
        
    - name: Run tests
      run: |
        python -m pytest test.py -v 